services:
  irods-server:
    container_name: irods-server
    image: "ghcr.io/wtsi-npg/ub-16.04-irods-4.2.7:latest"
    platform: linux/amd64
    restart: always
    ports:
      - "127.0.0.1:1247:1247"
      - "127.0.0.1:20000-20199:20000-20199"

  baton:  
    image: baton
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu-16.04-dev
      args:
        APP_UID: 1000  # Your UID here
    volumes:
      - ".:/app"
    environment:
      IRODS_ENVIRONMENT_FILE: "/app/tests/.irods/irods_environment.json"
    depends_on:
      irods-server:
        condition: service_healthy
